export type TPaymentSuccess = {
  tran_id: "TXID-415641";
  val_id: "250411182639lUyEijesTmYsUZD";
  amount: "200.00";
  card_type: "BKASH-BKash";
  store_amount: "195.00";
  card_no: "";
  bank_tran_id: "250411182639izRFKdVIR1UYFq9";
  status: "VALID";
  tran_date: "2025-04-11 18:26:31";
  error: "";
  currency: "BDT";
  card_issuer: "BKash Mobile Banking";
  card_brand: "MOBILEBANKING";
  card_sub_brand: "Classic";
  card_issuer_country: "Bangladesh";
  card_issuer_country_code: "BD";
  store_id: "shope66e1c6d624595";
  verify_sign: "0291707cda6e9259d5bc4621afaa10ba";
  verify_key: "amount,bank_tran_id,base_fair,card_brand,card_issuer,card_issuer_country,card_issuer_country_code,card_no,card_sub_brand,card_type,currency,currency_amount,currency_rate,currency_type,error,risk_level,risk_title,status,store_amount,store_id,tran_date,tran_id,val_id,value_a,value_b,value_c,value_d";
  verify_sign_sha2: "5e5850ae3635e87166db1a85d1b8cc332ea1d4f0ed787f4894eaf5c603cab2dc";
  currency_type: "BDT";
  currency_amount: "200.00";
  currency_rate: "1.0000";
  base_fair: "0.00";
  value_a: "";
  value_b: "";
  value_c: "";
  value_d: "";
  subscription_id: "";
  risk_level: "0";
  risk_title: "Safe";
};

export type TSslPayload = {
  tran_id: string;
  val_id: string;
  amount: string;
  card_type: string;
  store_amount: string;
  card_no: string;
  bank_tran_id: string;
  status: string;
  tran_date: string;
  error: string;
  currency: string;
  card_issuer: string;
  card_brand: string;
  card_sub_brand: string;
  card_issuer_country: string;
  card_issuer_country_code: string;
  store_id: string;
  verify_sign: string;
  verify_key: string;
  verify_sign_sha2: string;
  currency_type: string;
  currency_amount: string;
  currency_rate: string;
  base_fair: string;
  value_a: string;
  value_b: string;
  value_c: string;
  value_d: string;
  subscription_id: string;
  risk_level: string;
  risk_title: string;
  card_ref_id: string;
};
